### ISSUE TITLE
Adding table of content for long pages

### ISSUE THREAD

**Issue by judykong97** [ASSETS-Conference/assets2022#27] opened 2022-02-14 23:27 UTC
Potentially using https://tscanlin.github.io/tocbot/ for the long pages. Look into it and check if it is accessible.

**Comment by jonfroehlich** [comment] 2022-02-15 00:18
There might be other ToC generators/libraries as well.

But I generally think this is pretty important to the readability/consumability of our webpages. Many are long and densely filled with content. We appropriately use H1s, H2s, to help organize things but lack a way of easily navigating around a page.

I noticed that Amy Ko has a nice left-sidebar ToC on some of their book pages: https://faculty.washington.edu/ajko/books/user-interface-software-and-technology/

I use tocbot on my physcomp teaching website, which dynamically appears on the right side when you scroll down a webpage: https://makeabilitylab.github.io/physcomp/advancedio/oled.html (not on mobile, however).

**Comment by jonfroehlich** [comment] 2022-02-16 13:39
Some pages that would really benefit from either a floating ToC or a leftsidebar TOC include:

- [Code of Conduct](https://assets-conference.github.io/assets2022/assets22-v1/code-of-conduct.html)
- [Policy on Program Committees](https://assets-conference.github.io/assets2022/assets22-v1/policy-on-committees.html)
- [Mentoring](https://assets-conference.github.io/assets2022/assets22-v1/mentoring.html)
- [Technical Papers](https://assets-conference.github.io/assets2022/assets22-v1/technical-papers.html)
- And beyond...

Alternatively, if we can't get an accessible left sidebar ToC or floating ToC to work, perhaps we have a ToC at the top of the page like my teaching website has:
![image](https://user-images.githubusercontent.com/1621749/154276116-1eb2855b-b85d-4f80-b728-58a9bb8a3cf9.png)

**Comment by jonfroehlich** [comment] 2022-03-09 21:58
I personally still think this would be nice... but it's a "bonus" TODO so I understand if y'all don't think it's doable.

**Comment by ArkaneCow** [comment] 2022-03-21 02:09
I did some early work on this feature on the branch jason-wu/add-toc-to-pages using a boostrap plugin called bootstrap TOC. It has some nifty features such as scroll following.

As @jonfroehlich said, there are a couple of possibilities and I wonder which one we should go with.

Below are some rough layouts I looked at (without the final styling)

Scroll pane: 
![image](https://user-images.githubusercontent.com/1429346/159196484-c67382a0-5cf4-4da7-aa45-95538622f7c1.png)

Before content:
![image](https://user-images.githubusercontent.com/1429346/159196542-67477d52-6008-4175-a946-c2245c9e4577.png)

Floating would look roughly like the following, except the righthand background would match the content like the official [bootstrap website](https://getbootstrap.com/docs/5.0/customize/components/):
![image](https://user-images.githubusercontent.com/1429346/159196668-09bffa1c-a9b5-422f-9657-f1c681a319b0.png)


Some pros/cons i see for each:

Scroll pane:
+ always visible to the user
+ doesn't push page contents back
+ relatively easy to implement
- might not work as well on mobile, but can be disabled

Before content:
+ easiest to implement
+ reasonable placement a la Wikipedia, jon's course website
+ will be consistent on mobile/small screens
- if the toc is too long, it can occlude the page's content

Floating is similar to Scroll pane, except the content would be aligned with the vertical center of the page, rather than the vertical center of the pane occupied by the content. From other examples of [Scroll pane TOCs](https://getbootstrap.com/docs/5.0/customize/components/), the content is left-aligned because centered content would look weird if not centered with the page. Therefore, floating would probably be preferred over scroll since the rest of the website is all page-center aligned.

**Comment by EdigaHe** [comment] 2022-03-21 22:05
Thanks @ArkaneCow for all the quick implementations. 

I personally like the left-sided scroll pane (the first one) on desktop but I can also see how it will be problematic on mobile. Can we use the "scroll pane" on desktop and "before content" on mobile? If we use "before content", I think adding a floating "back to top" button to the page would be great. 

Also, I'm not sure if the floating elements would be accessible on both desktop and mobile?

**Comment by EdigaHe** [comment] 2022-03-21 22:14
@jonfroehlich  What do you think?

**Comment by jonfroehlich** [comment] 2022-03-21 22:45
I'd personally like to try out having both the TOC centered at the top of the page and a floating left-side bar like [the demo page](https://getbootstrap.com/docs/5.0/customize/components/) @ArkaneCow linked to. The left-side bar is top priority (compared to TOC at the top of the page).

For the left-side bar, we may need to either use shorter H1s/H2s (so update the content of the page) or have "short names" that show up on the left sidebar (more work). As now, the headings are so large that they don't work very well as selectable menu content.

For the centered TOC at the top of the page, perhaps you can look at my [teaching website for an example aesthetic](https://makeabilitylab.github.io/physcomp/advancedio/oled.html) (though we'd probably only want to do H1s rather than H1-H3s as doing the latter pushes the content too far down on the page).

**Comment by ArkaneCow** [comment] 2022-07-25 07:41
Hey everyone, I went ahead and implemented this for one page (code of conduct) on the jason-wu/add-toc-to-pages branch and made the nav bar sticky. Here is a demo version of the page: https://jasonwunix.com/test/assets2022/code-of-conduct.html any suggestions before I apply it to other pages? Perhaps the text could be slightly bigger and as @jonfroehlich suggested, we could change the copyrighting of the headers so that they fit better.

**Comment by jonfroehlich** [comment] 2022-07-25 16:58
Thanks Jason!

I think we're moving in the right direction. Three quick comments/concerns:

1. How does this affect screen readers? I think we could just hide this entire element from screen readers `aria-hidden="true"` because screen readers will provide linear navigation based on headers anyway.

2. When you fully enlarge the page (which is how I view it by default; I'm primarily a desktop user with external monitors), the TOC looks quite strange and way too far left. Thoughts? I think we have to constrain it to a maximum left position if the browser is at a certain width.
![image](https://user-images.githubusercontent.com/1621749/180833151-4619932e-28ca-485a-b3e9-96d40ca7cb28.png)

3. Similarly, I'm not sure I like that the TOC gets inserted into the top of the page when the browser window has a small width.
![image](https://user-images.githubusercontent.com/1621749/180833260-ba8ddc05-ce16-45bf-831c-73d9dc284173.png)

Compare this, for example, with the floating sidebar menu on the [bootstrap website](https://getbootstrap.com/docs/5.0/customize/components/) (as just one example).

Full width:
![image](https://user-images.githubusercontent.com/1621749/180833425-6a325c5a-b3be-41ff-86ea-0abcf80a513e.png)

Laptop width:
![image](https://user-images.githubusercontent.com/1621749/180833471-8369d9da-4be8-4841-b70f-0b370950b470.png)

Small width:
![image](https://user-images.githubusercontent.com/1621749/180833502-cf43c243-05f9-4319-8784-63760592b698.png)

**Comment by ArkaneCow** [comment] 2022-07-26 06:21
Thank you for the great suggestions!
I added aria-hidden to the latest version (although some more thorough ax testing is still needed) and experimented with some new things.

In the newer versions, I made the nav bar appear narrower. I wonder what the best solution is for wide screens. I like the way the bootstrap sidebar looks in the full-width screenshot you posted, but their website has an all-white background which matches the side-bar background.

Here are two prototypes: 
1. https://jasonwunix.com/test/assets2022/code-of-conduct.html (makes the nav bar "hug" the content and move it closer to the center. Maybe in the final version the right part of the page background should also match the main content?)
2. https://jasonwunix.com/test/assets2022/code-of-conduct2.html (original version that hugs the left side of the screen)

Any thoughts on which one is prefrred? It's interesting to note that if you look at the older version of the same bootstrap doc page, it uses a behavior more similar to 2.: https://getbootstrap.com/docs/4.6/getting-started/introduction/

**Comment by jonfroehlich** [comment] 2022-07-26 13:07
Thanks @ArkaneCow. I think probably Option 2 is best (unless Option 1 purely floats above the page and has the alternating purplish background behind it).

Great observation with regards to the older version of the Boostrap page ([link](https://getbootstrap.com/docs/4.6/getting-started/introduction/)); however, they used left aligned content so it looks better at various page scales (similar to my [teaching website](https://makeabilitylab.github.io/physcomp/arduino/led-on.html)).

**Large**
![image](https://user-images.githubusercontent.com/1621749/181011544-ff95d01e-0484-4e08-9e3e-0d34106af713.png)

**Medium**
![image](https://user-images.githubusercontent.com/1621749/181011582-7b2606f2-9f92-4798-bf16-75f445bfccf4.png)

**Small**
![image](https://user-images.githubusercontent.com/1621749/181011632-f34e8d1b-afd5-43e8-bab6-708fe3b8334d.png)

Versus our `code-of-conduct2.html`, which looks, I think, a bit discombobulated at larger widths:

![image](https://user-images.githubusercontent.com/1621749/181011834-8ae78acd-b2e3-474e-9f3a-fab7d78fa9c0.png)

Some solutions: we do a better job centering the content between the header and the content part of the page. Here's one option for centering (based on header location):

![image](https://user-images.githubusercontent.com/1621749/181012806-a631fabf-c714-4adc-a1db-c33addf0ad71.png)

Another option for centering based on width of page (minus sidebar)—so maybe all we need to fix here is where we center the menu and header:

![image](https://user-images.githubusercontent.com/1621749/181012935-3556951f-cdad-48c2-8946-eaa4f90ec089.png)

Finally, a third option is to left align stuff rather than center it when the sidebar is activated. This is actually how Bootstrap and my website pull off a cleaner, more organized aesthetic.

**Comment by jayhersk** [comment] 2022-07-26 23:14
I think the alignment issue has been fixed in the current version! I also created a quick mockup for how this could look fully styled.

Current:
![Screen Shot 2022-07-26 at 7 01 02 PM](https://user-images.githubusercontent.com/15851295/181127736-e5a7bb14-eb90-4848-80b2-9f3c06939251.png)

Mockup idea:
![mockup-sidebar](https://user-images.githubusercontent.com/15851295/181127824-976ef210-9bf1-4a85-807a-ff6d0813d820.png)

**Comment by jonfroehlich** [comment] 2022-07-26 23:19
I think this looks excellent @jayhersk and perhaps works best at various page widths and is what I meant when I said:

> unless Option 1 purely floats above the page and has the alternating background behind it

Can we try a version of this in code?

**Comment by jonfroehlich** [comment] 2022-07-27 18:44
Let's also make sure to auto-hide the TOC for mobile

**Comment by jayhersk** [comment] 2022-08-05 18:17
Added styled version to code-of-conduct2.html:
![Screen Shot 2022-08-05 at 2 14 32 PM](https://user-images.githubusercontent.com/15851295/183137108-f1daff41-e759-4fe8-8494-6a3c648d2bba.png)

It stays on the left side of the page, and as the page scrolls it moves down to follow and stay visible. 
![Screen Shot 2022-08-05 at 2 14 48 PM](https://user-images.githubusercontent.com/15851295/183137119-66841b26-f617-4f4f-b1db-7049c84847ce.png)
When the page is too narrow to fit the sidebar in the margin, it disappears. If needed, we can later make it so it moves to the top of the page when the page is too narrow.

If this looks okay, we can finish implementing it by organizing the css and js into separate files, and adding it to the rest of the pages!

**Comment by jonfroehlich** [comment] 2022-08-05 20:35
Is this deployed anywhere? I tried testing it here:
* https://jasonwunix.com/test/assets2022/code-of-conduct2.html
* and here: https://assets-conference.github.io/assets2022/code-of-conduct2.html

But I didn't see the new version there...

**Comment by ArkaneCow** [comment] 2022-08-05 21:57
Hey Jon. I just added it here: https://jasonwunix.com/test/assets2022/code-of-conduct2.html#policy-against-harassment

**Comment by jonfroehlich** [comment] 2022-08-05 22:18
It looks totally awesome!
![image](https://user-images.githubusercontent.com/1621749/183217884-fd5557a9-26e7-4fc4-9019-90dd2fb95327.png)

I would say the one small thing is that when I go fullscreen on this 27" monitor, things don't look great. 
![image](https://user-images.githubusercontent.com/1621749/183218370-84788cf0-a3fe-4f30-8fdf-65bdf79bbffa.png)

Any reason why we don't just set the x location based on the location of the highlighted container below (maybe to an x-offset based on that, so it's not anchored to the left side of the window):
![image](https://user-images.githubusercontent.com/1621749/183218349-511254c1-a03e-46a6-9e10-b8f14aedfa55.png)

So, like:
![image](https://user-images.githubusercontent.com/1621749/183218535-2b1659b4-0a26-4a8b-8f24-0588c800c14d.png)

**Comment by jonfroehlich** [comment] 2022-08-08 21:15
This looks excellent. A few things before we ship:

- Did you make sure it's hidden from screen readers?
- What pages do we want this integrated into? I think it's valuable on nearly every page personally... but definitely for [Attending Overview](https://assets22.sigaccess.org/attending-overview.html), [Registration](https://assets22.sigaccess.org/registration.html), [Attending in Athens](https://assets22.sigaccess.org/attending-athens.html), [Policy on Committees](https://assets22.sigaccess.org/policy-on-committees.html), [Code of Conduct](https://assets22.sigaccess.org/code-of-conduct.html), and any others that you think would benefit! :)

https://user-images.githubusercontent.com/1621749/183515512-60a41c40-6b57-4215-8659-f7383f453857.mp4

**Comment by ArkaneCow** [comment] 2022-08-09 06:06
confirmed that the nav bar is hidden from screen readers. i will add the table of contents to those pages tomorrow and push them to the testing site

**Comment by jonfroehlich** [comment] 2022-08-09 11:58
Perfect. Thanks!

**Comment by ArkaneCow** [comment] 2022-08-10 00:43
I've added the TOC bot code and great work Jaylin did to those pages. The code is pushed to the feature branch and I put it on a test server here: https://jasonwunix.com/test/assets2022 . if it looks good, we can merge into main and push to the production server!

**Comment by jonfroehlich** [comment] 2022-08-10 13:04
I think it looks extraordinarily awesome. We should look out for more pages to integrate it into (any page that is particularly long and would benefit from the "outline" on the left and sidebar navigation).

I say push it to production! Thank you @ArkaneCow and @jayhersk for humoring me with this request to try and improve the navigability of our website. Awesome stuff! 🎉

**Comment by ArkaneCow** [comment] 2022-08-10 16:43
The feature is now merged into the main branch and live on the website! https://assets22.sigaccess.org/

**Closed by ArkaneCow** 2022-08-10 16:43 UTC
Labels: medium priority

**Comment by jonfroehlich** [comment] 2022-08-10 17:14
Yay! Thanks for all the great work!
